# common
spring:
  batch:
    jdbc.initialize-schema: always
    job.enabled: false

---

# local
spring:
  profiles: local

batch:
  daily-use-rate-stat:
    enabled: false

  weekly-use-rate-stat:
    enabled: true
    chunk-size: 10
