# local
spring:
  config:
    activate:
      on-profile: local
  batch:
    jdbc.initialize-schema: always
    job.enabled: false

batch:
  daily-use-rate-stat:
    enabled: false

  weekly-use-rate-stat:
    enabled: false
    chunk-size: 10

server:
  error:
    whitelabel:
      enabled: false
  port: 8081
