# local
spring:
  config:
    activate:
      on-profile: dev
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db.url}
    username: ${db.user}
    password: ${db.password}
  jpa:
    hibernate:
      direct: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: none
    database: mysql
    hikari:
      maximum-pool-size: 20
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
  servlet:
    multipart:
      max-file-size: 4000MB
      max-request-size: 4000MB

server:
  error:
    whitelabel:
      enabled: false
  port: 8080
  servlet:
    context-path: /api

# logging
logging:
  level:
    org.hibernate: DEBUG
    # org.hibernate.type.descriptor.sql: trace # Binding 값
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
